version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "npm"
    directory: "services/gateway"
    schedule:
      interval: "weekly"
    target-branch: "dev"
  - package-ecosystem: "pip"
    directory: "services/text-tools-service-py"
    schedule:
      interval: "weekly"
    target-branch: "dev"
